<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-L9I71BEA" name="com.lima.test.AdjunoLIMAForwarderReferenceTest" tests="50" failures="6" timestamp="2 Feb 2018 12:31:25 GMT" time="1066.857" errors="2">
  <testcase name="test_20_VerifyConatinerAwaitingStaus" time="11.740" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_36_checkStatus" time="3.000" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	***** Test Id :36 -  In PO Status Page&quot;PO Number&quot; Status is not matched as &quot;Shipped&quot; ***** expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	***** Test Id :36 -  In PO Status Page"PO Number" Status is not matched as "Shipped" ***** expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lima.test.AdjunoLIMAForwarderReferenceTest.test_36_checkStatus(AdjunoLIMAForwarderReferenceTest.java:908)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_36_checkStatus -->
  <testcase name="test_44_verifyGridForwarder" time="29.534" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	***** Test ID : 44 - In Forwarder Reference Tool the selected ETA value under Select Chevron does not match with ETA value displayed in Reference Chevron under GirdForwarder Details Grid ***** expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	***** Test ID : 44 - In Forwarder Reference Tool the selected ETA value under Select Chevron does not match with ETA value displayed in Reference Chevron under GirdForwarder Details Grid ***** expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lima.test.AdjunoLIMAForwarderReferenceTest.test_44_verifyGridForwarder(AdjunoLIMAForwarderReferenceTest.java:1112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_44_verifyGridForwarder -->
  <testcase name="verifyExixtanceOFChevrons" time="1.079" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_14_VerifyStatusReferencedSearchData" time="85.552" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_25_VerifyForwardReferenceMandatory" time="7.395" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_10_VerifyMultipleCriteriaSearchData" time="29.637" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_12_VerifyMultipleInvalidCriteriaSearchData" time="18.296" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_15_VerifyConatinerSearchData" time="29.011" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_42_Click_ReferenceTab" time="14.981" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_32_AccessEdit" time="40.863" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_28_VerifyShipQtyAndCtnInPOLink" time="1.114" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_50_checkForward" time="4.289" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_29_VerifyMandatory" time="11.434" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_43_verifyGridsInReferenceChevron" time="0.344" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_24_verifyGridForwarder" time="17.518" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_59_verifyHyperLink" time="40.693" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	***** Test ID : 37 - In Shipped Page&quot;PO Number Hyperlink&quot; Field is not found ***** expected [true] but found [false],
	*****_37_In Shipped page &quot;Po Number&quot;field is not a hyperLink***** expected [true] but found [false],
	***** Test ID : 37 - In Shipped Page&quot;Container Hyperlink&quot; Field is not found ***** expected [true] but found [false],
	*****_37_*****_37_In Shipped page &quot;Po Number&quot;field is not a hyperLink*****In Shipped page &quot;Container&quot;field is not a hyperLink***** expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	***** Test ID : 37 - In Shipped Page"PO Number Hyperlink" Field is not found ***** expected [true] but found [false],
	*****_37_In Shipped page "Po Number"field is not a hyperLink***** expected [true] but found [false],
	***** Test ID : 37 - In Shipped Page"Container Hyperlink" Field is not found ***** expected [true] but found [false],
	*****_37_*****_37_In Shipped page "Po Number"field is not a hyperLink*****In Shipped page "Container"field is not a hyperLink***** expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lima.test.AdjunoLIMAForwarderReferenceTest.test_59_verifyHyperLink(AdjunoLIMAForwarderReferenceTest.java:1378)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_59_verifyHyperLink -->
  <testcase name="test_53_AccessEdit" time="40.422" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_54_clickForwardReference" time="19.080" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_27_ClickHyperLink" time="5.742" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_18_VerifyConatinerSearchData" time="11.928" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_26_VerifyPoHyperLink" time="0.438" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_45_VerifyForwardReferenceMandatory" time="9.122" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_22_verifyGridsInReferenceChevron" time="0.391" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_60_clickPONumberHyperLink" time="36.603" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest">
    <error type="org.openqa.selenium.WebDriverException" message="window.ArenaForms is undefined
Command duration or timeout: 94 milliseconds
Build info: version: &#039;2.53.1&#039;, revision: &#039;a36b8b1&#039;, time: &#039;2016-06-30 17:32:46&#039;
System info: host: &#039;LAPTOP-L9I71BEA&#039;, ip: &#039;192.168.1.16&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_121&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 8daef7a5-b7a7-4a5c-9c97-c73431d118ee">
      <![CDATA[org.openqa.selenium.WebDriverException: window.ArenaForms is undefined
Command duration or timeout: 94 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:32:46'
System info: host: 'LAPTOP-L9I71BEA', ip: '192.168.1.16', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 8daef7a5-b7a7-4a5c-9c97-c73431d118ee
	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.lima.library.AdjunoUILibrary.getElemetValue(AdjunoUILibrary.java:513)
	at com.lima.pagefactory.AdjunoLIMAForwarderReferencePOM.getFieldValue(AdjunoLIMAForwarderReferencePOM.java:993)
	at com.lima.test.AdjunoLIMAForwarderReferenceTest.test_60_clickPONumberHyperLink(AdjunoLIMAForwarderReferenceTest.java:1391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: org.openqa.selenium.WebDriverException: window.ArenaForms is undefined
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:32:46'
System info: host: 'LAPTOP-L9I71BEA', ip: '192.168.1.16', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
	at <anonymous class>.anonymous(https://uat-lima46.adjuno.com/default.aspx?Guid=c25f39191fdc48be9587f6743cb2b422&MenuId=&Action=FindRequest&ActionOption=PO+Status&Reference=ACTIVITYLIMAUAT46_00160 line 69 > Function:1)
	at <anonymous class>.handleEvaluateEvent(https://uat-lima46.adjuno.com/default.aspx?Guid=c25f39191fdc48be9587f6743cb2b422&MenuId=&Action=FindRequest&ActionOption=PO+Status&Reference=ACTIVITYLIMAUAT46_00160:69)
]]>
    </error>
  </testcase> <!-- test_60_clickPONumberHyperLink -->
  <testcase name="test_35_verifyPONumber" time="32.836" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_48_ClickPOHyperLink" time="5.834" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_23_verifyGridForwarder" time="30.068" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	***** Test ID : 23 - In Forwarder Reference Tool the selected ETA value under Select Chevron does not match with ETA value displayed in Reference Chevron under GirdForwarder Details Grid ***** expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	***** Test ID : 23 - In Forwarder Reference Tool the selected ETA value under Select Chevron does not match with ETA value displayed in Reference Chevron under GirdForwarder Details Grid ***** expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lima.test.AdjunoLIMAForwarderReferenceTest.test_23_verifyGridForwarder(AdjunoLIMAForwarderReferenceTest.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_23_verifyGridForwarder -->
  <testcase name="test_9_VerifySingleCriteriaSearchData" time="65.887" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_57_verifyPONumber" time="30.952" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_52_GetReference_Num" time="8.628" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_41_verifyContainerNoWithReferenceStatus" time="25.698" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_37_verifyHyperLink" time="40.912" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	***** Test ID : 37 - In Shipped Page&quot;PO Number Hyperlink&quot; Field is not found ***** expected [true] but found [false],
	*****_37_In Shipped page &quot;Po Number&quot;field is not a hyperLink***** expected [true] but found [false],
	***** Test ID : 37 - In Shipped Page&quot;Container Hyperlink&quot; Field is not found ***** expected [true] but found [false],
	*****_37_*****_37_In Shipped page &quot;Po Number&quot;field is not a hyperLink*****In Shipped page &quot;Container&quot;field is not a hyperLink***** expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	***** Test ID : 37 - In Shipped Page"PO Number Hyperlink" Field is not found ***** expected [true] but found [false],
	*****_37_In Shipped page "Po Number"field is not a hyperLink***** expected [true] but found [false],
	***** Test ID : 37 - In Shipped Page"Container Hyperlink" Field is not found ***** expected [true] but found [false],
	*****_37_*****_37_In Shipped page "Po Number"field is not a hyperLink*****In Shipped page "Container"field is not a hyperLink***** expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lima.test.AdjunoLIMAForwarderReferenceTest.test_37_verifyHyperLink(AdjunoLIMAForwarderReferenceTest.java:952)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_37_verifyHyperLink -->
  <testcase name="test_8_VerifyExistanceOfFields" time="7.602" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_1_AccessForwardReference" time="30.897" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_7_VerifyExistanceOfFields" time="11.517" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_62_verifyContainerNoWithAwaitingStatus" time="33.802" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_33_clickForwardReference" time="21.253" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_61_clickContainerNoHyperLink" time="18.489" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_21_Click_Reference" time="13.508" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_31_GetReference_Num" time="8.485" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_30_SetForwardRef" time="19.977" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_63_verifyContainerNoWithReferenceStatus" time="30.437" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_58_checkStatus" time="3.125" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	***** Test Id :58 -  In PO Status Page&quot;PO Number&quot; Status is not matched as &quot;Shipped&quot; ***** expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	***** Test Id :58 -  In PO Status Page"PO Number" Status is not matched as "Shipped" ***** expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lima.test.AdjunoLIMAForwarderReferenceTest.test_58_checkStatus(AdjunoLIMAForwarderReferenceTest.java:1335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- test_58_checkStatus -->
  <testcase name="test_11_VerifySingleInvalidCriteriaSearchData" time="16.746" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_40_verifyContainerNoWithAwaitingStatus" time="38.415" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_38_clickPONumberHyperLink" time="36.599" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest">
    <error type="org.openqa.selenium.WebDriverException" message="window.ArenaForms is undefined
Command duration or timeout: 109 milliseconds
Build info: version: &#039;2.53.1&#039;, revision: &#039;a36b8b1&#039;, time: &#039;2016-06-30 17:32:46&#039;
System info: host: &#039;LAPTOP-L9I71BEA&#039;, ip: &#039;192.168.1.16&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_121&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 8daef7a5-b7a7-4a5c-9c97-c73431d118ee">
      <![CDATA[org.openqa.selenium.WebDriverException: window.ArenaForms is undefined
Command duration or timeout: 109 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:32:46'
System info: host: 'LAPTOP-L9I71BEA', ip: '192.168.1.16', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 8daef7a5-b7a7-4a5c-9c97-c73431d118ee
	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.lima.library.AdjunoUILibrary.getElemetValue(AdjunoUILibrary.java:513)
	at com.lima.pagefactory.AdjunoLIMAForwarderReferencePOM.getFieldValue(AdjunoLIMAForwarderReferencePOM.java:993)
	at com.lima.test.AdjunoLIMAForwarderReferenceTest.test_38_clickPONumberHyperLink(AdjunoLIMAForwarderReferenceTest.java:965)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: org.openqa.selenium.WebDriverException: window.ArenaForms is undefined
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:32:46'
System info: host: 'LAPTOP-L9I71BEA', ip: '192.168.1.16', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: unknown
	at <anonymous class>.anonymous(https://uat-lima46.adjuno.com/default.aspx?Guid=c25f39191fdc48be9587f6743cb2b422&MenuId=&Action=FindRequest&ActionOption=PO+Status&Reference=ACTIVITYLIMAUAT46_00160 line 69 > Function:1)
	at <anonymous class>.handleEvaluateEvent(https://uat-lima46.adjuno.com/default.aspx?Guid=c25f39191fdc48be9587f6743cb2b422&MenuId=&Action=FindRequest&ActionOption=PO+Status&Reference=ACTIVITYLIMAUAT46_00160:69)
]]>
    </error>
  </testcase> <!-- test_38_clickPONumberHyperLink -->
  <testcase name="test_39_clickContainerNoHyperLink" time="18.471" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_51_EditForwardReferenceValue" time="19.588" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
  <testcase name="test_2_verifyDropDownExistance" time="26.925" classname="com.lima.test.AdjunoLIMAForwarderReferenceTest"/>
</testsuite> <!-- com.lima.test.AdjunoLIMAForwarderReferenceTest -->
